### ISSUE TITLE
How to set up basic federating implementation?

### ISSUE THREAD

**Issue by singpolyma** [pump-io/pump.io#1130]
Hi there!

I've found the /api/user/username/feed JSON that one could poll to get user's content as it is published, but having trouble figuring out the flow to "follow" and have new content pushed to my implementation.  Is this documented somewhere I can't find?  Or just pointing me at the right part of the code could be very helpful.  Thanks!

**Comment by strugee** [comment]
Does `API.md` not have what you want?

**Comment by singpolyma** [comment]
@strugee it talks about how to get the feed, but not how to register to get notified of updates to the feed, or where said updates expect to go.

**Comment by larjona** [comment]
You have to post an activity with a certain verb (post, follow...)

Some links that may help:
https://github.com/e14n/pump.io/blob/master/API.md#creating-an-activity
https://github.com/e14n/pump.io/wiki#cookbook

Some implementations you can take as reference:
https://github.com/e14n/pump.io/tree/master/bin
https://pypump.readthedocs.org/en/latest/

Hope that helps!

**Comment by singpolyma** [comment]
@larjona right, ok, so I post this update to their inbox, and then they do webfinger lookup on me and in the future post all their updates to my inbox?

**Comment by cathalgarvey** [comment]
Just poking this issue: I'd love to learn a little more about how Pump.io aims to do federation, too.

I've committed a little personal time to try and hack up an OStatus library in Go, and after that I'd like to see if I can make a microstatus OStatus server like unto GNUSocial, too.

In parallel, I'm wondering how hard a "Federation Bridge" server would be, that could tie together platforms like OStatus and Pump.io and let people cross-follow again.

(aside: OStatus, Pumpio and Diaspora really need to agree on a "following standard" so that GNUSocial people can click "follow" on Pump users, and vice versa without confusion..)

**Comment by larjona** [comment]
@cathalgarvey There is a working 'bridge' from pump.io to GNU Social, maybe having a look at the code may help you: https://github.com/e14n/pump2status
About the 'common standard', it's being worked on, in the W3C Social Group: https://www.w3.org/Social/WG Their meeting notes are public and I think they have an IRC channel where hopefully you can get info about the progress in that area.

**Comment by strugee** [comment]
@singpolyma can I close this issue, since this discussion petered out long ago? Or did you need something else?
