### ISSUE TITLE
YouTube thumbnails videos are not well integrated in the web UI

### ISSUE THREAD

**Issue by moshpirit** [pump-io/pump.io#1249]
The web UI is not working as I think it's supposed to since it repeat the thumbnails on others posts. For example, [here in my profile](https://1realtime.net/AlbertoAru), you only need to see my last 5 posts to realize what I'm talking about. 

Eg: here's there's no youtube link, but appears the thumbnail of a youtube video several posts above. 
![captura de pantalla - 041216 - 14 34 16](https://cloud.githubusercontent.com/assets/7888062/20866518/ea94f06e-ba2e-11e6-88a6-2dc59cec1e08.png)

Another example:

This is the thumbnail of a video I shared in [this note](https://1realtime.net/AlbertoAru/note/1Gq0mzW-SJypm3uOgake4A).
![captura de pantalla - 041216 - 14 36 07](https://cloud.githubusercontent.com/assets/7888062/20866534/3e0a4d20-ba2f-11e6-8c94-f1a8da9667cf.png)
And it's also repeated several times:
![captura de pantalla - 041216 - 14 36 52](https://cloud.githubusercontent.com/assets/7888062/20866538/4b41fc90-ba2f-11e6-8d69-2121a3a4488c.png)

**Comment by strugee** [comment]
This is now fixed in master but on second thought, we're going to leave this open - this bug really messes up the web UI and the fix is low-impact, so we might want to do a patch release for it soon-ish. (However currently I don't have the mental bandwidth for that, as my primary server's been down for multiple days and dealing with that has taken a lot of my energy.)

**Comment by strugee** [comment]
This was patched in 2.0.5.
