### ISSUE TITLE
pump.io/tryit is down

### ISSUE THREAD

**Issue by abliss** [pump-io/pump.io#1273]
Every pump server I've found so far exhorts me thus: "No pump.io account yet? Try it!" with a link to http://pump.io/tryit , but this link seems to be dead.

**Comment by strugee** [comment]
It's because most of the servers it redirects to are down. Nothing we can do about that.

Try datamost.com.

**Comment by oshepherd** [comment]
It would seem reasonable to cull the dead servers from the tryit list?

**Comment by abliss** [comment]
FYI I was able to create an account on datamost, but very little of the site seems to actually work.

**Comment by strugee** [comment]
@abliss see #1211 - try clearing your cookies

@oshepherd yeah, I'm not sure. I've thought about it and have left them there since we're planning to transfer them to community owners which should improve uptime a lot. That's taking long enough that I would support removing "dead" servers, but there's also the problem of how to actually define that - most of the E14N servers aren't dead _all_ of the time...

FYI according to https://pumpstatus.strugee.net (which isn't public yet; see phpservermon/phpservermon#51) the only E14N node that's up besides identi.ca is fmrl.me.

**Comment by LuckyPigeon** [comment]
I sent a pull request that may help to improve the situation: https://github.com/pump-io/pump-io.github.io/pull/4

**Comment by strugee** [comment]
This is fixed in the website.
