### ISSUE TITLE
Volume for uploaded files in Dockerfile

### ISSUE THREAD

**Issue by evanp** [pump-io/pump.io#1593]
In the Dockerfile, there should be a clearly defined volume used for the uploaded files, so they can be mounted on a volume by Docker.

**Comment by strugee** [comment]
@evanp you're going to be able to do this a lot faster than I am since I'm not super familiar with Docker volume management. Would you be able to take a look at this tomorrow? Then we can ship it with the Dockerfile in 5.1.1 - though now that I think about it making this kind of change is reeeeally stretching it for a patch release. What do you think?
