### ISSUE TITLE
Documentation Missing lots of admin information

### ISSUE THREAD

**Issue by tcreek** [pump-io/pump.io#1685]
Let's start off with this one in the Configuration value reference:

"secret: A session-generating secret, server-wide password."

This is the only place it is mentioned, and its description is meaningless to those who are not familiar with pump.io.  Exactly what is this for?

Next: Sysadmin Documentation

This section hardly contains anything on administering the site. For example, there is no mention if there is even a administrator portal and the default credentials, if there is any.

Also not mentioned at all is site customization which should be part of the Sysadmin Documentation.
Some admin portals provide means of limited customization. Example projects would be Word Press, or Zen Cart.

In addition, I see it is published in jade and node.js.
How about some tips/advice for editing the site? Suggested IDE, etc/?

Can we get something to get started properly on it than just install guide, and how to read logs?

Thanks

**Comment by strugee** [comment]
> For example, there is no mention if there is even a administrator portal and the default credentials, if there is any.

I added some stuff to the FAQ about this: https://pumpio.readthedocs.io/en/latest/sysadmins-faq.html

Is there anything else you feel should be covered?

> How about some tips/advice for editing the site? Suggested IDE, etc/?

Recommending development environments seems like it's going to far, but we certainly could do a better job of telling people how to patch the Jade. This has been tracked for a while in https://gitlab.com/pump.io/pump-docs/issues/10 and I've added a note about Jade.

> "secret: A session-generating secret, server-wide password."

Filed https://gitlab.com/pump.io/pump-docs/issues/24

If you have any other questions, please feel free to file them on GitLab, or mention it on IRC so someone else can.

**Comment by tcreek** [comment]
> Is there an admin console?
>Nope. Administration is done via the commandline.

Should there not be a section , or expansion on what exactly you can administer via the command site which affects the site (pump.io) specifically? 

For the "secret" Maybe better explain what it is used for? It just makes me think it is for some sort of administration account. 

> Recommending development environments seems like it's going to far, but we certainly could do a better job of telling people how to patch the Jade. This has been tracked for a while in https://gitlab.com/pump.io/pump-docs/issues/10 and I've added a note about Jade.


I don't think suggesting how people can customize the site to get them  started is not going a bit far.
In fact helping people doing that will probably get more users. Why you think WordPress is so popular?

**Comment by strugee** [comment]
Sorry for the delay. Past couple weeks have been not so great... midterms, etc.

> Should there not be a section , or expansion on what exactly you can administer via the command site which affects the site (pump.io) specifically?

Just filed https://gitlab.com/pump.io/pump-docs/issues/24 to track this.

> I don't think suggesting how people can customize the site to get them started is not going a bit far.
> In fact helping people doing that will probably get more users. Why you think WordPress is so popular?

WordPress is an entirely different beast because it supports and embraces the concept of plugins. We technically support plugins but they're undocumented, in large part because neither Evan and I are convinced they're a good idea and we shouldn't drop them, even though they've admittedly been around for a good long while. See https://github.com/pump-io/pump.io/issues/588#issuecomment-19878947.

Patching the Jade is not akin to installing a plugin, WordPress or otherwise. It is functionally equivalent to patching the source code itself and while we'll support folks doing that as best as we can, it's not something we encourage people to do or support officially. In fact, in [the changelog](https://github.com/pump-io/pump.io/blob/master/CHANGELOG.md) "Ability to merge trivial local template modifications" is mentioned, but I've been thinking for a while that we should drop that, because unlike the other items on the list it involves a lot of difficult and _extremely_ subjective decisions for each patch touching the web UI. Practically speaking it's difficult to version software that way. (I should point out that this is literally the first time I've ever voiced this idea, so other people may disagree with it.)

However what we _could_ do is more explicitly call out configuration values that are actually designed for site customization. Filed https://gitlab.com/pump.io/pump-docs/issues/26 for that.
