### ISSUE TITLE
Hilfreiche Nutzung von sozialen Netzwerken

### ISSUE THREAD

**Issue by horald** [pump-io/pump.io#1690]
Hallo zusammen,

ich würde gerne die sozialen Netzwerke nutzen. Netzwerke die frei, also Open Source, sicher, also verschlüsselt und dezentral sind. Dies ist aber leider nicht so einfach, da ich vieles nicht verstehe. Leider sind viele Netzwerkbetreiber nicht offen für Neulinge, sondern bilden Cliquen und schließen einem bei der ersten "dummen" Frage schon aus. Das ist aber für mich nicht sozial, sondern eher asozial. Ich möchte aber noch nicht aufgeben und stelle hier meine Fragen in der Hoffnung, dass es doch den ein oder anderen gibt, der sich die Mühe macht, sie mir zu beantworten.

- wie kann ich sehen wie viele Leute meinen Beitrag gelesen haben?
- wie kann ich eine geschlossene Gruppe bilden, so dass nur bestimmte Leute meinen Beitrag lesen können?
- wie lege ich selber ein Server an mit einer sicheren Verschlüsselung?
- wie kann ich nur Beiträge zu einem bestimmten Thema anzeigen?
- wie kann ich echte Freunde finden und diese nach bestimmten Themengebieten eingrenzen? Z. B. ich möchte Leute kennenlernen die sich mit dem Raspberry Pi beschäftigen.
- wie kann ich sehen wie viele Nutzer mit meinem Netzwerk verbunden sind und theoretisch meinen Beitrag lesen könnten?
- wie kann ich mich vor Mobbing schützen?
- welche Möglichkeiten habe ich mich vor Hasskommentare zu schützen?
- wie stelle ich sicher, dass die Kommentare nicht von Bots kommen?
- wo gibt es ein Wiki, wo ich Hilfe zur Nutzung des Netzwerkes finde?
- wie kann ich sehen, ob ein Beitrag oder Kommentar erfolgt ist?

Mein momentaner Kontakt ist bei friendica: https://squeet.me/profile/horald
Da ich diesen Kontakt aber nur selten aufrufe, ist es besser mir direkt eine Antwort per Mail zu schicken.
Für jede konkrete Antwort danke ich im Voraus.

Viele Grüße
Horst Meyer

==============================================================================================================

Helpful use of social networks

Hello everybody,

I'd like to use the social networks. Networks that are free, open source, secure, encrypted and decentralized. Unfortunately, this is not so easy, because I don't understand many things. Unfortunately, many network operators are not open to newcomers, but form cliques and exclude you from the first "stupid" question. For me, however, this is not social, but rather anti-social. But I don't want to give up yet and ask my questions here in the hope that there will be one or the other who takes the trouble to answer them.

- how can I see how many people have read my article?
- how can I form a closed group so that only certain people can read my contribution?
- how do I create a server myself with secure encryption?
- how can I only display posts on a specific topic?
- how can I find real friends and narrow them down by topic? For example, I would like to meet people who deal with the Raspberry Pi.
- how can I see how many users are connected to my network and could theoretically read my article?
- how can I protect myself against bullying?
- what possibilities do I have to protect myself from hate comments?
- how do I make sure that the comments don't come from bots?
- where is there a wiki where I can find help using the network?
- how can I see if a post or comment has been made?

My current contact is friendica: https://squeet.me/profile/horald
Since I rarely call this contact, it is better to send me an answer directly by mail.
Thank you in advance for any specific answer.
Sorry, but I prefer a german answer. Thank you.

Many greetings
Horst Meyer

**Comment by Serkan-devel** [comment]
>wie kann ich mich vor Mobbing schützen?

Man kann die die Anstößig verhaltenen nutzer blockier, dem Admin melden und falls es wirklich brennsig wird sogar der Poliyei melden.

>wo gibt es ein Wiki, wo ich Hilfe zur Nutzung des Netzwerkes finde?

Einer art Wiki finden Sie [hier](https://pumpio.readthedocs.io/en/latest/) und auch [hier](https://github.com/pump-io/pump.io/wiki)


Ich werde mich mit der Instanzsoftware hier noch mehr befassen.

**Comment by vxcamiloxv** [comment]
Interesting the list, for user guide check: https://pumpio.readthedocs.io/en/latest/userguide.html

**In pump.io:**

- how can I see how many people have read my article?
  -  no, and could be a privacy leak
- how can I form a closed group so that only certain people can read my contribution? 
  - pump.io support list, you can create a list a send a note only to that list
- how do I create a server myself with secure encryption?
  - check: https://pumpio.readthedocs.io/en/latest/sysadmins.html
- how can I only display posts on a specific topic?
  - no supported, but could be useful
- how can I find real friends and narrow them down by topic? For example, I would like to meet people who deal with the Raspberry Pi.
  - you can send an internal message
- how can I see how many users are connected to my network and could theoretically read my article?
  - no, you can't
- how can I protect myself against bullying?
  - pump.io does not support block users, yet
- what possibilities do I have to protect myself from hate comments?
   - unfollow a user
- how do I make sure that the comments don't come from bots?
   - hard, but pump.io is not common bots
-  how can I see if a post or comment has been made?
   - in activity view

**Comment by vxcamiloxv** [comment]
I'll close this ticket, if you need more support please reopen or better write on #pump.io irc channel or in the xmpp room: https://github.com/pump-io/pump.io/wiki/Community
