### ISSUE TITLE
Bad Request when trying to register

### ISSUE THREAD

**Issue by warpr** [pump-io/pump.io#455]
I'm still getting Bad Request when trying to register.  Looking in the network log of firefox or chrome I see the POST to http://pump.frob.nl/main/register .

Tested on commit 467b47e6c0dd5dec08a53aa99e00ecec72565d4a .

**Comment by KeinPfusch** [comment]
Yes, sure! It works now you run it under 443, meaning under root. Apart that you just messed the security for the whole server, now is ok and the issue can be closed.

yet another root...

**Comment by strugee** [comment]
@KeinPfusch this is not true. pump.io can drop privileges to a normal user. See the `serverUser` option on https://pumpio.readthedocs.io/en/latest/configuration/reference.html.

**Comment by KeinPfusch** [comment]
Still not related to the issue of security. I managed to install pump io with a decent security level, then since I don't like negative discussion, I wrote a guide, on how I run this software with a 3-tier architecture
and some hardening against privilege escalation attacks.

https://github.com/KeinPfusch/kp-howtos/blob/master/pump.io.md

**Comment by strugee** [comment]
@KeinPfusch so, I'm pretty disappointed to read this comment. From reading the document you linked you seem to have several fundamental misconceptions, both about this project and about security in general, so I'm going to leave some comments on the diff to clarify some of these things.

More generally though I'm upset that you chose to simply hurl insults at this project instead of engaging constructively. The issue tracker is open; instead of writing about everything you think we're doing wrong in a guide many people won't see, you could have filed issues telling us about those things directly. Maybe then you would've noticed [the security label](https://github.com/pump-io/pump.io/issues?q=is%3Aissue+is%3Aopen+label%3Asecurity) which I think shows the extent to which this project takes security seriously. Or even better, you could've sent code, or improved [the documentation](https://gitlab.com/pump.io/pump-docs), both of which are open for anyone. I'm open to feedback; I filed #1554 and #1555 specifically because your document reminded me to think about this stuff. But what has happened here contributes nothing to the project except for negativity.
