### ISSUE TITLE
OAuth temporary credentials are served up as text/plain

### ISSUE THREAD

**Issue by Screwtapello** [pump-io/pump.io#822]
When requesting OAuth temporary credentials (via the `/oauth/request_token` endpoint), the resulting credential data is served up with a `Content-Type` header set to `text/plain`.

RFC5849 says (in section 2.1):

> The temporary credentials are included in the HTTP response body using the "application/x-www-form-urlencoded" content type as defined by [W3C.REC-html40-19980424] with a 200 status code (OK).

I guess most people just blindly assume that whatever comes back with a 200 status code will be properly URL-encoded key-value pairs regardless of content-type, but it would be nice to have confirmation in the `Content-Type` header.

**Comment by ilpianista** [comment]
I just got this because [QtNetworkAuth](https://doc.qt.io/qt-5/qtnetworkauth-index.html) does expect [application/x-www-form-urlencoded](https://github.com/qt/qtnetworkauth/blob/5.8/src/oauth/qoauthoobreplyhandler.cpp#L76).

**Comment by strugee** [comment]
Marking as "near future" because this is pretty byte-sized and is causing real pain.

@ilpianista can you confirm that this is happening on a recent pump.io server?

**Comment by strugee** [comment]
I would also be happy to help anyone who wanted to send patches to fix this.

**Comment by ilpianista** [comment]
I would do, please tell where to start :-)

**Comment by strugee** [comment]
@ilpianista wonderful! https://github.com/pump-io/pump.io/blob/master/doc/CONTRIBUTING_CODE.md should get you set up and ready to contribute generally (you can skip the part about finding an issue obviously, since you'll be working on this one).

As for the code, you will want to poke around in [routes/oauth.js](https://github.com/pump-io/pump.io/blob/master/routes/oauth.js) - this file defines the functions that handle OAuth requests. For context, https://github.com/pump-io/pump.io/blob/f7da08e5038c7b3d15c19884087ab3acd7213ffd/lib/app.js#L436 is the location where these functions are used.

To be honest I've never looked at this part of the codebase so I'm not 100% sure what's going on (particularly since I don't quite grok OAuth yet) but I'm guessing you will have to set the `Content-Type` header somewhere in one of those functions. Express has a convenient method to do this: https://expressjs.com/en/api.html#res.type

Feel free to ping me on GitHub or on IRC if you need help. Good luck!

**Comment by ilpianista** [comment]
Thank you for sharing the first steps. Turns out the issue comes from _connect-auth_ which unfortunately doesn't seem maintained anymore. I opened a PR however.

**Comment by strugee** [comment]
@ilpianista oh, we actually maintain our own fork of connect-auth for that very reason. https://github.com/e14n/connect-auth

Been meaning to rip it out entirely (see #1321).

**Comment by ilpianista** [comment]
@strugee can you backport this to 3.0.x?

**Comment by strugee** [comment]
@ilpianista I don't think so, sorry :(

In 99% of cases it's [trivial][1] to upgrade to 4.x, and doing so will improve security and performance a _lot_. We really, really want people to be on 4.x or above. If anyone ever upgrades from 3.x to a later release of 3.x, instead of 4.x, that will generally speaking be the Wrong Thing to do. (You can see I pushed this while announcing the recent [security releases][2] too.)

 [1]: https://pumpio.readthedocs.io/en/latest/upgrades/3.x-to-4.x.html
 [2]: http://pump.io/blog/2017/05/pump.io-xss-security-releases-available
